[package]
name = "day5"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench_day5"
harness = false
